### ISSUE TITLE
Where to place extensions in the repo?

### ISSUE THREAD

**Issue by sblackler** [4Com/compose-remoting#4]
As per the title, I think we should begin to think about the structure for the extensions. I originally had the following structure in mind:

     src/
          Extensions/
               Transports/
               Providers/
          Compose.Remoting
          Compose.Remoting.Core

With the `tests/` folder mirroring the layout of the `src/` folder.

This is all assuming that we want the extensions in the same repo, or would we like them separate repo and then use the `Compose.Remoting.Core` NuGet package to build the extensions?

**Comment by mattridgway** [comment]
I would have separate repos, each with a single dependency to Core. I'm a fan of the separation and think it's just a little easier to pull and work on one thing. We have projects both ways at work, so not fussed if there is a particular want either way.

**Comment by sblackler** [comment]
I'm currently leaning towards a separate repo for the extensions. I know @Smudge202 has some thoughts on this as well around general structure and keeping with the logging

**Comment by Smudge202** [comment]
As I understand it, Transports are agnostic of Providers, and Providers agnostic of Transports. Although I understand why we might want to categorise them separately, in my opinion they are the same thing thing.

Whether it's an `AzureServiceBus` transport, or a `JsonSerializer`, they are both just implementations for `Compose.Remoting`'s abstractions.

I was going to suggest that all the extensions live under the same repository "like Serilog", however, I've only just noticed they don't do it like that anymore. A separate repo per project like @mattridgway suggests is much easier with regards to release tagging and build server publishing, so I'm all for that. Might follow suit on the other Compose projects if I can be assed to write up all the permission requests.

Further to this, I also propose collapsing Come.Remoting.Core into Compose.Remoting. 

I wonder if it should work in a similar fashion to Compose.Logging?

Compose.Logging does nothing on itself, but can be referenced by applications and services. Compose.Logging.SomeProvider is brought in by the host to actually form an output. Should remoting work the same way? Eliminate the need for Compose.Remoting vs Compose.Remoting.Core, because Core would become Compose.Remoting?

**Comment by sblackler** [comment]
Yeah I'm happy to have per extension repo's, I was on the fence for the most part.

As for the collapsing, I think we shouldn't be collapsing the libraries for the reason that any extension should not need to know about any of the defaults. For that reason, I believe I have sealed the appropriate classes to prevent this. Updates would also cause an issue, eg: we bugfix something in the defaults, the abstraction version then changes as well. Ideally, the abstractions version wouldn't change until we add functionality to it.

**Comment by Smudge202** [comment]
Think there's a range of subjects here, will try to break them out and respond to each.

The reason for not collapsing the Core project is that any Defaults specified by Compose.Remoting would be inherited by extension libraries. That's fair enough, though as with Compose.Logging and Compose itself, if the default providers are minimal and do not force dependencies on other packages, I don't see a problem with it.

Updating stuff is a subject all unto itself. Breaking changes should be avoided where possible (correct version increments if a breaking change cannot be avoided). This applies when updating anything exposed, be that an extensible implementation, or an public abstraction. I don't think code updates really play into this discussion, so I'd be tempted to save that one for another time?

**Comment by sblackler** [comment]
Unless @mattridgway has any objections, i'll collapse into a single package at some point this weekend? I'll also have a think of the extensions that I'd like to start out with and send it somebodies way for the internal requests etc.

Agreed that code updates are off-topic for this thread. Unless there are any objections to the merge, or any other points, think we can close this one off now

**Comment by smudge202** [comment]
Yup, constructive discussion. Will link this convo into the PR. @mattridgway can close the issue.

**Comment by mattridgway** [comment]
Yeah happy with this, looking forward to the updates in the PR
